# Generated by Django 5.1.6 on 2025-02-13 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
