# Generated by Django 5.1.6 on 2025-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_services_create_at_services_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('job', models.CharField(max_length=202)),
                ('compani', models.CharField(max_length=202)),
                ('lokations', models.CharField(max_length=202)),
                ('time', models.CharField(max_length=202)),
                ('data', models.CharField(max_length=202)),
                ('imag', models.FileField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
