# Generated by Django 5.1.6 on 2025-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_heppiclents'),
    ]

    operations = [
        migrations.AddField(
            model_name='heppiclents',
            name='discrptions',
            field=models.CharField(default=1, max_length=202),
            preserve_default=False,
        ),
    ]
